
SET NOCOUNT ON;
--DROP TABLE  dbo.METER_DATA;
CREATE TABLE dbo.METER_DATA (FILE_NM VARCHAR(1000), CITY VARCHAR(1000), BUILDING_TYPE VARCHAR(1000), RAW_DATA VARCHAR(MAX), TEMP_DATA VARCHAR(MAX), 
DATE_AS_STRING VARCHAR(500), "Electricity:Facility [J](Hourly)" VARCHAR(1000), "ElectricityNet:Facility [J](Hourly)" VARCHAR(1000), "Gas:Facility [J](Hourly)" VARCHAR(1000),
"InteriorLights:Electricity [J](Hourly)" VARCHAR(1000), "InteriorEquipment:Electricity [J](Hourly)" VARCHAR(1000),   
"Electricity:Facility [J](TimeStep)" VARCHAR(1000),
"Gas:Facility [J](TimeStep" VARCHAR(1000),
);

-- Get list of all files for meter data
DECLARE @command NVARCHAR(1000) = '';
DECLARE @currentIndex INT = 1;
DECLARE @maxIndex INT = 1;
DECLARE @currentFileName VARCHAR(1000) = '';
DECLARE @listOfFiles TABLE (ID INT IDENTITY(1,1), FILE_NM VARCHAR(1000));
INSERT INTO @listOfFiles (FILE_NM) EXEC XP_CMDSHELL 'DIR /S /B C:\Projects\Hackathon\Meters';

SET @maxIndex = (SELECT MAX(ID) FROM @listOfFiles); 
WHILE(@currentIndex <= @maxIndex)
BEGIN
	SET @currentFileName = (SELECT FILE_NM FROM @listOfFiles WHERE ID = @currentIndex);
	SET @command = 'TYPE ' + @currentFileName;
	INSERT INTO dbo.METER_DATA ( RAW_DATA) EXEC XP_CMDSHELL @command;
	UPDATE dbo.METER_DATA SET FILE_NM = @currentFileName WHERE FILE_NM IS NULL;
	SET @currentIndex = @currentIndex + 1;
END


-- CleanUp crap data
DELETE FROM dbo.METER_DATA WHERE RAW_DATA IS NULL;

UPDATE dbo.METER_DATA SET TEMP_DATA = RAW_DATA;
UPDATE dbo.METER_DATA SET DATE_AS_STRING = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.METER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, DATE_AS_STRING + ',', '');
UPDATE dbo.METER_DATA SET "Electricity:Facility [J](Hourly)"  = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.METER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "Electricity:Facility [J](Hourly)" + ',', '');
UPDATE dbo.METER_DATA SET "ElectricityNet:Facility [J](Hourly)" = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.METER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "ElectricityNet:Facility [J](Hourly)" + ',', '');
UPDATE dbo.METER_DATA SET "Gas:Facility [J](Hourly)" = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.METER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "Gas:Facility [J](Hourly)" + ',', '');
UPDATE dbo.METER_DATA SET "InteriorLights:Electricity [J](Hourly)"  = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.METER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "InteriorLights:Electricity [J](Hourly)" + ',', '');
UPDATE dbo.METER_DATA SET "InteriorEquipment:Electricity [J](Hourly)"  = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.METER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "InteriorEquipment:Electricity [J](Hourly)" + ',', '');
UPDATE dbo.METER_DATA SET "Electricity:Facility [J](TimeStep)" = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.METER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "Electricity:Facility [J](TimeStep)" + ',', '');
UPDATE dbo.METER_DATA SET "Gas:Facility [J](TimeStep"= TEMP_DATA;


-- Get BUILDING_TYPE
UPDATE DBO.METER_DATA SET BUILDING_TYPE = 'APARTMENT_HIGH_RISE' WHERE FILE_NM LIKE '%APARTMENTHIGHRISE%';
UPDATE DBO.METER_DATA SET BUILDING_TYPE = 'OFFICE_LARGE' WHERE FILE_NM LIKE '%OFFICE_LARGE%';
UPDATE DBO.METER_DATA SET BUILDING_TYPE = 'RETAIL_STRIP_MALL' WHERE FILE_NM LIKE '%RETAILSTRIPMALL%';


-- Get City
UPDATE dbo.METER_DATA  SET CITY = REPLACE(SUBSTRING(FILE_NM, LEN(FILE_NM) - CHARINDEX('_', REVERSE(FILE_NM)) + 2, 100), 'Meter.csv', '');



-- Update time
UPDATE dbo.METER_DATA  SET DATE_AS_STRING = CAST('2010/' + REPLACE(DATE_AS_STRING, '24:00','23:59') AS DATETIME) 
WHERE DATE_AS_STRING != 'Date/Time';


-- 
ALTER TABLE dbo.METER_DATA ADD DATE_AS_DATE DATETIME;
UPDATE dbo.METER_DATA  SET DATE_AS_DATE =  CAST(DATE_AS_STRING AS DATETIME) WHERE DATE_AS_STRING != 'Date/Time';


ALTER TABLE dbo.METER_DATA ADD TOTAL_JOULES DECIMAL(20,10);
UPDATE dbo.METER_DATA  SET TOTAL_JOULES = 
CAST(COALESCE(CEILING([Electricity:Facility [J]](Hourly)]), 0.000000) AS DECIMAL(20,10)) + 
CAST(COALESCE(CEILING([ElectricityNet:Facility [J]](Hourly)]),  0.000000) AS DECIMAL(20,10)) + 
CAST(COALESCE(CEILING([Gas:Facility [J]](Hourly)]),  0.000000) AS DECIMAL(20,10)) + 
CAST(COALESCE(CEILING([InteriorLights:Electricity [J]](Hourly)]), 0.000000) AS DECIMAL(20,10)) + 
CAST(COALESCE(CEILING([InteriorEquipment:Electricity [J]](Hourly)]), 0.000000) AS DECIMAL(20,10))
WHERE DATE_AS_STRING like '%:00%' AND LEN(TRIM("Electricity:Facility [J](Hourly)")) > 1


-- CLEANED
SELECT DISTINCT CITY, BUILDING_TYPE, DATE_AS_DATE, TOTAL_JOULES
INTO dbo.METER_DATA_CLEANED
FROM dbo.METER_DATA
WHERE TOTAL_JOULES IS NOT NULL


SELECT DISTINCT CITY, BUILDING_TYPE, CAST(DATE_AS_DATE AS DATE) AS DATE, SUM(TOTAL_JOULES) AS TOTAL_JOULES_PER_DAY
INTO dbo.METER_DATA_CLEANED_PER_DAY
FROM dbo.METER_DATA_CLEANED
GROUP BY CITY, BUILDING_TYPE,  CAST(DATE_AS_DATE AS DATE)
