SET NOCOUNT ON;
--DROP TABLE  dbo.MOER_DATA;
CREATE TABLE dbo.MOER_DATA (FILE_NM VARCHAR(1000), CITY VARCHAR(1000), BUILDING_TYPE VARCHAR(1000), RAW_DATA VARCHAR(MAX), TEMP_DATA VARCHAR(MAX), 
TIMESTAMP_AS_STRING VARCHAR(500), "MOER" VARCHAR(1000), "MOER VERSION" VARCHAR(1000), "frequency" VARCHAR(1000)
);

-- Get list of all files for meter data
DECLARE @command NVARCHAR(1000) = '';
DECLARE @currentIndex INT = 1;
DECLARE @maxIndex INT = 1;
DECLARE @currentFileName VARCHAR(1000) = '';
DECLARE @listOfFiles TABLE (ID INT IDENTITY(1,1), FILE_NM VARCHAR(1000));
INSERT INTO @listOfFiles (FILE_NM) EXEC XP_CMDSHELL 'DIR /S /B C:\Projects\Hackathon\MOER';

SET @maxIndex = (SELECT MAX(ID) FROM @listOfFiles); 
WHILE(@currentIndex <= @maxIndex)
BEGIN
	SET @currentFileName = (SELECT FILE_NM FROM @listOfFiles WHERE ID = @currentIndex);
	SET @command = 'TYPE ' + @currentFileName;
	INSERT INTO dbo.MOER_DATA ( RAW_DATA) EXEC XP_CMDSHELL @command;
	UPDATE dbo.MOER_DATA SET FILE_NM = @currentFileName WHERE FILE_NM IS NULL;
	SET @currentIndex = @currentIndex + 1;
END


-- CleanUp crap data
DELETE FROM dbo.MOER_DATA WHERE RAW_DATA IS NULL;

UPDATE dbo.MOER_DATA SET TEMP_DATA = RAW_DATA;
UPDATE dbo.MOER_DATA SET TIMESTAMP_AS_STRING = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.MOER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, TIMESTAMP_AS_STRING + ',', '');
UPDATE dbo.MOER_DATA SET "MOER"  = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.MOER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "MOER" + ',', '');
UPDATE dbo.MOER_DATA SET "MOER VERSION" = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.MOER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "MOER VERSION" + ',', '');
UPDATE dbo.MOER_DATA SET "frequency" = SUBSTRING(TEMP_DATA, 0, CHARINDEX(',', TEMP_DATA));
UPDATE dbo.MOER_DATA SET TEMP_DATA = REPLACE(TEMP_DATA, "frequency" + ',', '');

-- Get City
UPDATE dbo.MOER_DATA  SET CITY = 'ATLANTA' WHERE FILE_NM like  '%SOCO%';
UPDATE dbo.MOER_DATA  SET CITY = 'BUFFALO' WHERE FILE_NM like '%NYISO_WEST%';
UPDATE dbo.MOER_DATA  SET CITY = 'DENVER' WHERE FILE_NM like '%PSCO%';
UPDATE dbo.MOER_DATA  SET CITY = 'ELPASO' WHERE FILE_NM like '%WACM%';
UPDATE dbo.MOER_DATA  SET CITY = 'GREATFALLS' WHERE FILE_NM like '%MPCO%';
UPDATE dbo.MOER_DATA  SET CITY = 'MINNEAPOLIS' WHERE FILE_NM like '%MISO%';
UPDATE dbo.MOER_DATA  SET CITY = 'ROCHESTER' WHERE FILE_NM like '%NYISO_CENTRAL%';
UPDATE dbo.MOER_DATA  SET CITY = 'NEWYORK' WHERE FILE_NM like '%NYISO_NYC%';
UPDATE dbo.MOER_DATA  SET CITY = 'PROTANGELES' WHERE FILE_NM like '%BPA%';
UPDATE dbo.MOER_DATA  SET CITY = 'SANDIEGO' WHERE FILE_NM like '%CAISO%';
UPDATE dbo.MOER_DATA  SET CITY = 'SEATTLE' WHERE FILE_NM like '%SCL%';
UPDATE dbo.MOER_DATA  SET CITY = 'TAMPA' WHERE FILE_NM like '%TEC%';
UPDATE dbo.MOER_DATA  SET CITY = 'TUSCON' WHERE FILE_NM like '%TEPC%'; 


-- Get time
ALTER TABLE dbo.MOER_DATA ADD DATE_AS_DATE DATETIME;
UPDATE dbo.MOER_DATA  SET DATE_AS_DATE = CAST(SUBSTRING(REPLACE(TIMESTAMP_AS_STRING, 'T', ' '), 0, 20) AS DATETIME) 
WHERE LEN(TRIM(TIMESTAMP_AS_STRING)) > 1 AND TIMESTAMP_AS_STRING != 'timestamp'


-- CLEANED
SELECT DISTINCT CITY, MOER, DATE_AS_DATE
INTO dbo.MOER_DATA_CLEANED
FROM dbo.MOER_DATA
WHERE TIMESTAMP_AS_STRING LIKE '%00:00+%';



